services:
  api:
    build: .
    ports:
      - "8000:8000"   # expose API on port 8000
  
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"   # expose MLflow dashboard on port 5000
